### ISSUE TITLE
Running in pycharm

### ISSUE THREAD

**Issue by karsten01** [Juniorn1003/Email-Spammer#1]
When running in pycharm the program will not run past the asking for the email section. I've already changed 'clear' to 'cls' so that It works. I am new to python, so maybe I am just missing something, just thought I would let you know of this issue from a newbie.

**Comment by maxsptz** [comment]
Hey, i made a spammer myself as this repo is a bit outdated. It is written in python3+ and works in console. its also got an interface! If you have questions regarding running it in console, just read through my tutorial on my repo and ask any questions if needed! 
you can get it from [here](https://github.com/Curioo/emailpyspam)!

**Comment by complexpotato** [comment]
This script is meant for running in a Linux environment, hence won't work on other OS.
